<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile - CodeChallenger</title>
    <link rel="stylesheet" href="assets/css/styles.css">
    <link rel="stylesheet" href="assets/css/profile.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body>
<div class="app-container">
    <nav class="navbar">
        <div class="navbar-brand">
            <a href="${pageContext.request.contextPath}/">
                <img id="logo-img" src="${pageContext.request.contextPath}/assets/img/logo-black.png" width="150px"
                     alt="logo">
            </a>
        </div>

        <div class="navbar-menu">
            <div class="theme-toggle">
                <i class="fas fa-moon"></i>
            </div>

            <c:choose>
                <c:when test="${sessionScope.is_authenticated == true}">
                    <a href="${pageContext.request.contextPath}/profile">
                        <button class="btn btn-primary">Profile</button>
                    </a>
                    <form action="${pageContext.request.contextPath}/auth/logout">
                        <button type="submit" class="btn btn-primary">Logout</button>
                    </form>
                </c:when>
                <c:otherwise>
                    <a href="${pageContext.request.contextPath}/auth?tab=signin">
                        <button id="sign-in-btn" class="btn btn-primary">Sign In</button>
                    </a>
                    <a href="${pageContext.request.contextPath}/auth?tab=signup">
                        <button id="sign-up-btn" class="btn btn-primary">Sign Up</button>
                    </a>
                </c:otherwise>
            </c:choose>
        </div>
    </nav>

    <main class="profile-container">
        <div class="profile-header">
            <div class="profile-avatar">
                <i class="fas fa-user-circle"></i>
            </div>
            <div class="profile-info">
                <h2>john_developer</h2>
                <p>john.doe@example.com</p>
                <span class="role-badge">User</span>
            </div>
            <button id="edit-profile-btn" class="btn btn-primary">
                <i class="fas fa-edit"></i> Edit Profile
            </button>
        </div>

        <div class="profile-stats">
            <div class="stat-card">
                <div class="stat-icon">
                    <i class="fas fa-code"></i>
                </div>
                <div class="stat-content">
                    <h3>Problems Solved</h3>
                    <p>47</p>
                </div>
            </div>
            <div class="stat-card">
                <div class="stat-icon">
                    <i class="fas fa-tasks"></i>
                </div>
                <div class="stat-content">
                    <h3>Tests Completed</h3>
                    <p>12</p>
                </div>
            </div>
            <div class="stat-card">
                <div class="stat-icon">
                    <i class="fas fa-fire"></i>
                </div>
                <div class="stat-content">
                    <h3>Current Streak</h3>
                    <p>7 days</p>
                </div>
            </div>
            <div class="stat-card">
                <div class="stat-icon">
                    <i class="fas fa-trophy"></i>
                </div>
                <div class="stat-content">
                    <h3>Best Streak</h3>
                    <p>23 days</p>
                </div>
            </div>
        </div>

        <div class="activity-section">
            <h3>Activity Overview</h3>
            <div class="activity-grid" id="activity-grid">
                <!-- Static activity grid will be generated by JavaScript -->
            </div>
            <div class="activity-legend">
                <span>Less</span>
                <div class="legend-squares">
                    <div class="activity-square level-0"></div>
                    <div class="activity-square level-1"></div>
                    <div class="activity-square level-2"></div>
                    <div class="activity-square level-3"></div>
                    <div class="activity-square level-4"></div>
                </div>
                <span>More</span>
            </div>
        </div>

        <div class="recent-activity">
            <h3>Recent Activity</h3>
            <div class="activity-list">
                <div class="activity-item">
                    <div class="activity-icon">
                        <i class="fas fa-code"></i>
                    </div>
                    <div class="activity-content">
                        <p class="activity-description">Solved "Two Sum" problem</p>
                        <span class="activity-time">2 hours ago</span>
                    </div>
                </div>
                <div class="activity-item">
                    <div class="activity-icon">
                        <i class="fas fa-tasks"></i>
                    </div>
                    <div class="activity-content">
                        <p class="activity-description">Completed Java Basics Test with 85% score</p>
                        <span class="activity-time">1 day ago</span>
                    </div>
                </div>
                <div class="activity-item">
                    <div class="activity-icon">
                        <i class="fas fa-code"></i>
                    </div>
                    <div class="activity-content">
                        <p class="activity-description">Solved "Binary Search" problem</p>
                        <span class="activity-time">1 day ago</span>
                    </div>
                </div>
                <div class="activity-item">
                    <div class="activity-icon">
                        <i class="fas fa-code"></i>
                    </div>
                    <div class="activity-content">
                        <p class="activity-description">Solved "Merge Sort" problem</p>
                        <span class="activity-time">2 days ago</span>
                    </div>
                </div>
                <div class="activity-item">
                    <div class="activity-icon">
                        <i class="fas fa-user-edit"></i>
                    </div>
                    <div class="activity-content">
                        <p class="activity-description">Updated profile information</p>
                        <span class="activity-time">3 days ago</span>
                    </div>
                </div>
                <div class="activity-item">
                    <div class="activity-icon">
                        <i class="fas fa-tasks"></i>
                    </div>
                    <div class="activity-content">
                        <p class="activity-description">Completed Data Structures Test with 92% score</p>
                        <span class="activity-time">4 days ago</span>
                    </div>
                </div>
                <div class="activity-item">
                    <div class="activity-icon">
                        <i class="fas fa-code"></i>
                    </div>
                    <div class="activity-content">
                        <p class="activity-description">Solved "Fibonacci Sequence" problem</p>
                        <span class="activity-time">5 days ago</span>
                    </div>
                </div>
                <div class="activity-item">
                    <div class="activity-icon">
                        <i class="fas fa-code"></i>
                    </div>
                    <div class="activity-content">
                        <p class="activity-description">Solved "Palindrome Check" problem</p>
                        <span class="activity-time">6 days ago</span>
                    </div>
                </div>
                <div class="activity-item">
                    <div class="activity-icon">
                        <i class="fas fa-code"></i>
                    </div>
                    <div class="activity-content">
                        <p class="activity-description">Solved "Array Rotation" problem</p>
                        <span class="activity-time">1 week ago</span>
                    </div>
                </div>
                <div class="activity-item">
                    <div class="activity-icon">
                        <i class="fas fa-tasks"></i>
                    </div>
                    <div class="activity-content">
                        <p class="activity-description">Completed Algorithms Test with 78% score</p>
                        <span class="activity-time">1 week ago</span>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <!-- Edit Profile Modal -->
    <div class="modal" id="edit-profile-modal">
        <div class="modal-content">
            <div class="modal-header">
                <h3>Edit Profile</h3>
                <button class="close-btn">&times;</button>
            </div>
            <div class="modal-body">
                <form id="edit-profile-form">
                    <div class="form-group">
                        <label for="edit-username">Username</label>
                        <input type="text" id="edit-username" value="john_developer" required>
                    </div>
                    <div class="form-group">
                        <label for="edit-email">Email</label>
                        <input type="email" id="edit-email" value="john.doe@example.com">
                    </div>
                    <div class="form-group">
                        <label for="edit-bio">Bio</label>
                        <textarea id="edit-bio" rows="3" placeholder="Tell us about yourself...">Passionate Java developer with 3+ years of experience. Love solving algorithmic challenges and building scalable applications.</textarea>
                    </div>
                    <div class="form-group">
                        <label for="edit-location">Location</label>
                        <input type="text" id="edit-location" value="San Francisco, CA" placeholder="City, Country">
                    </div>
                    <div class="form-group">
                        <label for="edit-website">Website</label>
                        <input type="url" id="edit-website" value="https://johndoe.dev"
                               placeholder="https://yourwebsite.com">
                    </div>
                    <div class="form-actions">
                        <button type="button" class="btn btn-outline" id="cancel-edit-btn">Cancel</button>
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        // Generate static activity grid
        function generateStaticActivityGrid() {
            const activityGrid = document.getElementById('activity-grid');

            // Static activity data for demonstration
            const staticActivityData = {
                // Recent days with high activity
                '2024-01-15': 4, '2024-01-14': 3, '2024-01-13': 2, '2024-01-12': 1,
                '2024-01-11': 3, '2024-01-10': 2, '2024-01-09': 4, '2024-01-08': 1,
                '2024-01-07': 2, '2024-01-06': 3, '2024-01-05': 1, '2024-01-04': 2,
                '2024-01-03': 4, '2024-01-02': 3, '2024-01-01': 2,

                // December 2023
                '2023-12-31': 1, '2023-12-30': 2, '2023-12-29': 3, '2023-12-28': 1,
                '2023-12-27': 2, '2023-12-26': 1, '2023-12-25': 0, '2023-12-24': 1,
                '2023-12-23': 3, '2023-12-22': 2, '2023-12-21': 4, '2023-12-20': 3,
                '2023-12-19': 2, '2023-12-18': 1, '2023-12-17': 2, '2023-12-16': 3,
                '2023-12-15': 1, '2023-12-14': 2, '2023-12-13': 4, '2023-12-12': 3,
                '2023-12-11': 2, '2023-12-10': 1, '2023-12-09': 3, '2023-12-08': 2,
                '2023-12-07': 1, '2023-12-06': 2, '2023-12-05': 3, '2023-12-04': 1,
                '2023-12-03': 2, '2023-12-02': 4, '2023-12-01': 3,

                // November 2023 (some gaps)
                '2023-11-30': 2, '2023-11-29': 1, '2023-11-28': 3, '2023-11-27': 2,
                '2023-11-26': 0, '2023-11-25': 0, '2023-11-24': 1, '2023-11-23': 2,
                '2023-11-22': 3, '2023-11-21': 1, '2023-11-20': 2, '2023-11-19': 4,
                '2023-11-18': 3, '2023-11-17': 2, '2023-11-16': 1, '2023-11-15': 3,
                '2023-11-14': 2, '2023-11-13': 1, '2023-11-12': 0, '2023-11-11': 0,
                '2023-11-10': 2, '2023-11-09': 3, '2023-11-08': 1, '2023-11-07': 2,
                '2023-11-06': 4, '2023-11-05': 3, '2023-11-04': 2, '2023-11-03': 1,
                '2023-11-02': 3, '2023-11-01': 2,

                // October 2023
                '2023-10-31': 1, '2023-10-30': 2, '2023-10-29': 3, '2023-10-28': 1,
                '2023-10-27': 2, '2023-10-26': 4, '2023-10-25': 3, '2023-10-24': 2,
                '2023-10-23': 1, '2023-10-22': 3, '2023-10-21': 2, '2023-10-20': 1,
                '2023-10-19': 2, '2023-10-18': 3, '2023-10-17': 1, '2023-10-16': 2,
                '2023-10-15': 4, '2023-10-14': 3, '2023-10-13': 2, '2023-10-12': 1,
                '2023-10-11': 3, '2023-10-10': 2, '2023-10-09': 1, '2023-10-08': 2,
                '2023-10-07': 3, '2023-10-06': 1, '2023-10-05': 2, '2023-10-04': 4,
                '2023-10-03': 3, '2023-10-02': 2, '2023-10-01': 1
            };

            // Generate 365 days
            const today = new Date('2024-01-15'); // Fixed date for static demo
            const startDate = new Date(today);
            startDate.setDate(today.getDate() - 364);

            activityGrid.innerHTML = '';

            for (let i = 0; i < 365; i++) {
                const currentDate = new Date(startDate);
                currentDate.setDate(startDate.getDate() + i);
                const dateStr = currentDate.toISOString().split('T')[0];

                const square = document.createElement('div');
                square.className = 'activity-square';

                const activityCount = staticActivityData[dateStr] || 0;
                let level = 0;

                if (activityCount > 0) {
                    if (activityCount >= 4) level = 4;
                    else if (activityCount >= 3) level = 3;
                    else if (activityCount >= 2) level = 2;
                    else level = 1;
                }

                square.classList.add(`level-${level}`);
                square.title = `${dateStr}: ${activityCount} activities`;

                activityGrid.appendChild(square);
            }
        }

        // Modal functionality
        const editProfileBtn = document.getElementById('edit-profile-btn');
        const editProfileModal = document.getElementById('edit-profile-modal');
        const editProfileForm = document.getElementById('edit-profile-form');
        const cancelEditBtn = document.getElementById('cancel-edit-btn');
        const closeBtn = document.querySelector('.close-btn');

        function openEditModal() {
            editProfileModal.classList.add('active');
        }

        function closeEditModal() {
            editProfileModal.classList.remove('active');
        }

        function saveProfile(e) {
            e.preventDefault();
            alert('Profile updated successfully! (This is a static demo)');
            closeEditModal();
        }

        // Event listeners
        editProfileBtn.addEventListener('click', openEditModal);
        cancelEditBtn.addEventListener('click', closeEditModal);
        closeBtn.addEventListener('click', closeEditModal);
        editProfileForm.addEventListener('submit', saveProfile);

        // Close modal when clicking outside
        editProfileModal.addEventListener('click', (e) => {
            if (e.target === editProfileModal) {
                closeEditModal();
            }
        });

        generateStaticActivityGrid();
    });
</script>

<script src="assets/js/theme.js"></script>

</body>
</html>
